highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Shahraiar Karim Saurov's Resume
name: Shahraiar Karim Saurov
email: shahriarksaurov@gmail.com
email_full: shahriarksaurov@gmail.com
website: github.io/ShahSau
website_full: https://github.io/ShahSau
github: 
twitter: 
tel: +358452249949
tel_full: tel:+358452249949
google_maps: 'https://goo.gl/maps/zWjE9ZrJmXA5REL37'
address:
  street: Ida Aalbergintie 1, 1D
  postcode: '00400'
  city: Helsinki
  country: Finland
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]

theme: jekyll-theme-hacker
